### ISSUE TITLE
TTF/OTF of built-in fonts

### ISSUE THREAD

**Issue by Myrronth** [ActiveLook/Activelook-API-Documentation#1]
I want to use the built-in fonts in graphical tools to make UI mockups and designs. Is there a TTF/OTF version of the built-in fonts that you can provide?

**Comment by bonjourx** [comment]
The built-in font is Computer Modern Sans Serif. The sizes are:
Font 1  24px
Font 2  36px
Font 3  48px

We will update the documentation in a future release.
Thank you so much for your feedback.
