### ISSUE TITLE
Typo error in Gauge section

### ISSUE THREAD

**Issue by blkfribourg** [ActiveLook/Activelook-API-Documentation#10]
First, thanks for providing such a great API documentation ! 👍 
I noticed a small error in the gauge section (5.11. Gauge):
In the provided example, the save layout frame command ID should be 0x60 and not 0x63 (=clear layout).

**Comment by tcubizolle-microoled** [comment]
Hello,

We will fix it as soon as possible.

Thank you for your feedback!
