### ISSUE TITLE
Animation with GIF format

### ISSUE THREAD

**Issue by mobile-appz** [ActiveLook/Activelook-API-Documentation#9]
How can one use a GIF animation file to display animation on the device? I'm using the iOS example app and SDK but there don't seem to be any animation examples? It would be very helpful if you could please a high level overview of how to achieve this? Or ideally, a full iOS implementation.

**Comment by SylvainRomillon** [comment]
The functionality to save animations with the iOS SDK is not yet implemented.

The easiest way to do this is to create your own configuration with the [Config-Generator](https://github.com/ActiveLook/Config-Generator), obtain a configuration file, and then upload it to the glasses.

I have just pushed an example to the `dev` branch :[AnimationCommandsViewController.swift](https://github.com/ActiveLook/demo-app/blob/dev/ios/example/AnimationCommandsViewController.swift)

**Comment by mobile-appz** [comment]
> The functionality to save animations with the iOS SDK is not yet implemented.
> 
> The easiest way to do this is to create your own configuration with the [Config-Generator](https://github.com/ActiveLook/Config-Generator), obtain a configuration file, and then upload it to the glasses.
> 
> I have just pushed an example to the `dev` branch :[AnimationCommandsViewController.swift](https://github.com/ActiveLook/demo-app/blob/dev/ios/example/AnimationCommandsViewController.swift)

Great, thanks for your help
